### ISSUE TITLE
[v6 rc] Not able to use new rc - Error: this package itself specifies a `main` module field that could not be resolved

### ISSUE THREAD

**Issue by Jobeso** [callstack/react-native-fbads#156]
When trying out the newest release from npm I encounter this error.
`this package itself specifies a 'main' module field that could not be resolved`

<details><summary>stack trace</summary>
<p>

```
Error: While trying to resolve module `react-native-fbads` from file `/Users/myuser/projects/myapp/app/modules/ads/components/FBNativeAd.js`, the package `/Users/myuser/projects/myapp/node_modules/react-native-fbads/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/myuser/projects/myapp/node_modules/react-native-fbads/dist/lib/index.js`. Indeed, none of these files exist:

  * `/Users/myuser/projects/myapp/node_modules/react-native-fbads/dist/lib/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/Users/myuser/projects/myapp/node_modules/react-native-fbads/dist/lib/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (/Users/myuser/projects/myapp/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:61:15)
    at DependencyGraph.resolveDependency (/Users/myuser/projects/myapp/node_modules/metro/src/node-haste/DependencyGraph.js:218:16)
    at Object.resolve (/Users/myuser/projects/myapp/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/Users/myuser/projects/myapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/myuser/projectsmyapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /Users/myuser/projects/myapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/Users/myuser/projects/myapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)
    at /Users/myuser/projects/myapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:309:15
```

</p>
</details>

So I thought of transpiling it because it looks like the ts files are not transpiled. When executing `yarn tsc` I get the following errors:

<details><summary>stack trace</summary>
<p>

```
node_modules/@types/react-native/globals.d.ts:36:15 - error TS2300: Duplicate identifier 'FormData'.

36 declare class FormData {
                 ~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:5078:11
    5078 interface FormData {
                   ~~~~~~~~
    'FormData' was also declared here.

node_modules/@types/react-native/globals.d.ts:66:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'body' must be of type 'string | ArrayBuffer | ArrayBufferView | Blob | FormData | URLSearchParams | ReadableStream | null | undefined', but here has type 'string | ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | Blob | FormData | null | undefined'.

66   body?: BodyInit_;
     ~~~~

node_modules/@types/react-native/globals.d.ts:92:14 - error TS2300: Duplicate identifier 'RequestInfo'.

92 declare type RequestInfo = Request | string;
                ~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:17604:6
    17604 type RequestInfo = Request | string;
               ~~~~~~~~~~~
    'RequestInfo' was also declared here.

node_modules/@types/react-native/globals.d.ts:111:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'Response' must be of type '{ new (body?: string | ArrayBuffer | ArrayBufferView | Blob | FormData | URLSearchParams | ReadableStream | null | undefined, init?: ResponseInit | undefined): Response; prototype: Response; error(): Response; redirect(url: string, status?: number | undefined): Response; }', but here has type '{ new (body?: string | ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | Blob | FormData | null | undefined, init?: ResponseInit | undefined): Response; prototype: Response; error: () => Response; redirect: (url: ...'.

111 declare var Response: {
                ~~~~~~~~

node_modules/@types/react-native/index.d.ts:9077:11 - error TS2451: Cannot redeclare block-scoped variable 'console'.

9077     const console: Console;
               ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:17295:13
    17295 declare var console: Console;
                      ~~~~~~~
    'console' was also declared here.

node_modules/@types/react-native/index.d.ts:9085:18 - error TS2717: Subsequent property declarations must have the same type.  Property 'geolocation' must be of type 'Geolocation', but here has type 'GeolocationStatic'.

9085         readonly geolocation: Geolocation;
                      ~~~~~~~~~~~

node_modules/@types/react-native/index.d.ts:9088:11 - error TS2451: Cannot redeclare block-scoped variable 'navigator'.

9088     const navigator: Navigator;
               ~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:17191:13
    17191 declare var navigator: Navigator;
                      ~~~~~~~~~
    'navigator' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:5078:11 - error TS2300: Duplicate identifier 'FormData'.

5078 interface FormData {
               ~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:36:15
    36 declare class FormData {
                     ~~~~~~~~
    'FormData' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:5088:13 - error TS2300: Duplicate identifier 'FormData'.

5088 declare var FormData: {
                 ~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:36:15
    36 declare class FormData {
                     ~~~~~~~~
    'FormData' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:16316:11 - error TS2320: Interface 'Window' cannot simultaneously extend types 'GlobalFetch' and 'WindowOrWorkerGlobalScope'.
  Named property 'fetch' of types 'GlobalFetch' and 'WindowOrWorkerGlobalScope' are not identical.

16316 interface Window extends EventTarget, WindowTimers, WindowSessionStorage, WindowLocalStorage, WindowConsole, GlobalEventHandlers, IDBEnvironment, WindowBase64, GlobalFetch, WindowOrWorkerGlobalScope, WindowEventHandlers {
                ~~~~~~

node_modules/typescript/lib/lib.dom.d.ts:17191:13 - error TS2451: Cannot redeclare block-scoped variable 'navigator'.

17191 declare var navigator: Navigator;
                  ~~~~~~~~~

  node_modules/@types/react-native/index.d.ts:9088:11
    9088     const navigator: Navigator;
                   ~~~~~~~~~
    'navigator' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:17295:13 - error TS2451: Cannot redeclare block-scoped variable 'console'.

17295 declare var console: Console;
                  ~~~~~~~

  node_modules/@types/react-native/index.d.ts:9077:11
    9077     const console: Console;
                   ~~~~~~~
    'console' was also declared here.

node_modules/typescript/lib/lib.dom.d.ts:17604:6 - error TS2300: Duplicate identifier 'RequestInfo'.

17604 type RequestInfo = Request | string;
           ~~~~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:92:14
    92 declare type RequestInfo = Request | string;
                    ~~~~~~~~~~~
    'RequestInfo' was also declared here.

node_modules/typescript/lib/lib.dom.iterable.d.ts:67:11 - error TS2300: Duplicate identifier 'FormData'.

67 interface FormData {
             ~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:36:15
    36 declare class FormData {
                     ~~~~~~~~
    'FormData' was also declared here.
```

</p>
</details>

**Comment by Suraj-Tiwari** [comment]
Pleas confirm files on corresponding location. Issue could be related to Ts
lint compile.

go to 'node_modules/react-native-fbads'
run 'npm install --only=dev'
then run 'npm run tsc'

**Comment by Suraj-Tiwari** [comment]
I hade same error while compiling but somehow it compiled.
I'll try to have a look at it tomorrow

**Comment by Jobeso** [comment]
Thanks for the suggested fix. Still fails for me. The packager gives the following error but the first mentioned error is gone. The transpile warnings still occur. Build fails, too.

<details><summary>stack trace</summary>
<p>

```
UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/myuser/projects/myapp/node_modules/react-native-fbads/node_modules/react-native/package.json collides with /Users/myuser/projects/myapp/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/Users/myuser/projects/myapp/node_modules/metro/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/Users/myuser/projects/myapp/node_modules/metro/node_modules/jest-haste-map/build/index.js:512:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:10558) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10558) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10558) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/myuser/projects/myapp/node_modules/react-native-fbads/node_modules/react-native/package.json collides with /Users/myuser/projects/myapp/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/Users/myuser/projects/myapp/node_modules/metro/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/Users/myuser/projects/myapp/node_modules/metro/node_modules/jest-haste-map/build/index.js:512:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:10558) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

```

</p>
</details>

**Comment by Suraj-Tiwari** [comment]
@erandagan  I've tested it, looks like there is some issue. Can you test it from your side?

**Comment by erandagan** [comment]
Hey, a few things:
1. @Trancever Did you transpile TS to JS prior to publishing?
2. @Jobeso 
It seems like these errors come from the React Native type definitions and not ours. We should probably configure TS to ignore those. PRs welcome :)

Anyway, TSC should compile the files even if these errors arise and you should be able to use the package.

**Comment by Trancever** [comment]
@Jobeso Could you check if it still happens on 6.0.1-RC version?

@erandagan I didn't so it was probably the issue.

**Comment by erandagan** [comment]
@Jobeso Could you try checking out the master branch for now, until the next RC is published?

**Comment by Jobeso** [comment]
So I was able to use the master branch after forking and changing the package version to semver convention `6.0.2-rc.1`. So I suggest handling upcoming rc versions like that. Before that `yarn` wouldn't let me install from the repo. 
Now I am able to successfully build even with the ts errors on transpiling.
Thanks for the help!
